version: '3'

networks:
  reverse-proxy-network:
    driver: bridge

services:
  network_placeholder:
    image: alpine:3.14
    command: "/bin/sh -c 'while true; do echo placeholder for keeping network alive. TODO ; sleep 10 ; done'"
    container_name: network_placeholder
    networks:
      - reverse-proxy-network
